version: "3"
services:
  bitcoind:
    build: .
    ports:
      - "8333:8333"
    volumes: 
      - bitcoind:/var/lib/bitcoind
    image: sugarjig/bitcoind:0.16.1
    deploy:
      mode: global
volumes:
  bitcoind: {}
